### ISSUE TITLE
Add small test data

### ISSUE THREAD

**Issue by alneberg** [nf-core/seqinspector#9]
### Description of feature

That can be used for smaller tests.

**Comment by KarNair** [comment]
Test data with MiSeq and NovaSeq6000 has been added at [https://github.com/KarNair/test-datasets/tree/seqinspector](https://github.com/KarNair/test-datasets/tree/seqinspector)

**Comment by Aratz** [comment]
@KarNair your branch should be merged into the `seqinspector` branch of https://github.com/nf-core/test-datasets (instead of your fork) and the link at https://github.com/nf-core/seqinspector/blob/d169eefc354c9aa7232b5abcbed3f67be3ac996f/conf/test.config#L25 should be updated accordingly. I'm reopening this issue to avoid this going under the radar.

**Comment by Aratz** [comment]
Or actually I don't enough rights to reopen, maybe one needs to be a repo admin for that?
